import { useQuery } from "@tanstack/react-query";
import { headToHeadPairKey, type HeadToHeadRecord } from "../domain/allTimeRecords";

interface AllTimeH2hSnapshot {
  generatedAt: string;
  records: Record<string, HeadToHeadRecord>;
}

const TWENTY_FOUR_HOURS_MS = 24 * 60 * 60 * 1000;

/**
 * Reads the precomputed all-time (every season) head-to-head snapshot —
 * public/data/all-time-h2h.json, generated by
 * scripts/generate-all-time-h2h.ts on a schedule (see
 * .github/workflows/all-time-h2h-snapshot.yml), same "static file shipped
 * with the build" pattern as public/data/player-status/.
 *
 * This used to be computed live in the browser, on every Home load, by
 * fetching every season's full rosters/users/matchups — that's what stalled
 * the Home screen on a cold cache (one manager's cold load could mean N
 * rivalry cards x M seasons of independent fetch pipelines). One static
 * ~10KB file fetched once is instant by comparison, at the cost of being
 * at most a day stale (fine for an all-time record, which only changes
 * once a game goes final).
 */
export function useAllTimeHeadToHead(ownerIdA: string, ownerIdB: string) {
  const query = useQuery({
    queryKey: ["allTimeH2hSnapshot"],
    queryFn: async () => {
      const res = await fetch("/data/all-time-h2h.json");
      if (!res.ok) throw new Error(`all-time-h2h.json fetch failed: ${res.status}`);
      return (await res.json()) as AllTimeH2hSnapshot;
    },
    staleTime: TWENTY_FOUR_HOURS_MS,
    gcTime: Infinity,
  });

  const record = query.data?.records[headToHeadPairKey(ownerIdA, ownerIdB)] ?? null;

  return { record, isLoading: query.isLoading };
}
